<a href="https://colab.research.google.com/github/MOHITH-KVS/dataanalysis_projects/blob/main/pandas_learning_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project: Student Performance Analysis using Pandas

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
std = pd.read_csv('student_performance.csv')

In [4]:
std

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
0,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39,38,40,44,45,75,2
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93,97,87,100,100,94,7
2,ST003,Rahul Patel,Female,ECE,3,A,19,71,81,72,80,96,85,6
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
4,ST005,Harsha Iyer,Male,CSE,1,C,19,87,67,87,63,72,79,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ST496,Kiran Rao,Male,AI & ML,1,B,22,73,76,72,87,100,96,6
496,ST497,Priya Reddy,Female,CSE,1,B,21,66,58,56,57,73,81,3
497,ST498,Rohit Gupta,Male,EEE,2,A,21,47,59,58,60,62,76,2
498,ST499,Akhil Naidu,Male,AI & ML,2,C,20,77,94,100,93,82,94,6
499,ST500,Sai Naidu,Female,CSE,1,B,18,87,100,78,82,97,97,6

In [5]:
std.head()

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
0,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39,38,40,44,45,75,2
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93,97,87,100,100,94,7
2,ST003,Rahul Patel,Female,ECE,3,A,19,71,81,72,80,96,85,6
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
4,ST005,Harsha Iyer,Male,CSE,1,C,19,87,67,87,63,72,79,5

In [6]:
std.tail()

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
495,ST496,Kiran Rao,Male,AI & ML,1,B,22,73,76,72,87,100,96,6
496,ST497,Priya Reddy,Female,CSE,1,B,21,66,58,56,57,73,81,3
497,ST498,Rohit Gupta,Male,EEE,2,A,21,47,59,58,60,62,76,2
498,ST499,Akhil Naidu,Male,AI & ML,2,C,20,77,94,100,93,82,94,6
499,ST500,Sai Naidu,Female,CSE,1,B,18,87,100,78,82,97,97,6

In [7]:
std.shape

(500, 14)

In [8]:
std.size

7000

In [9]:
std.columns

Index(['Student_ID', 'Student_Name', 'Gender', 'Department', 'Year', 'Section',
       'Age', 'Math', 'Physics', 'Chemistry', 'English', 'Biology',
       'Attendance', 'Study_Hours'],
      dtype='object')

In [10]:
std.ndim

2

In [11]:
std.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    500 non-null    object
 1   Student_Name  500 non-null    object
 2   Gender        500 non-null    object
 3   Department    500 non-null    object
 4   Year          500 non-null    int64
 5   Section       500 non-null    object
 6   Age           500 non-null    int64
 7   Math          500 non-null    int64
 8   Physics       500 non-null    int64
 9   Chemistry     500 non-null    int64
 10  English       500 non-null    int64
 11  Biology       500 non-null    int64
 12  Attendance    500 non-null    int64
 13  Study_Hours   500 non-null    int64
dtypes: int64(9), object(5)
memory usage: 54.8+ KB

In [12]:
len(std)

500

In [13]:
len(std.columns)

14

In [14]:
std.isnull()

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [15]:
std.isnull().sum()

Student_ID      0
Student_Name    0
Gender          0
Department      0
Year            0
Section         0
Age             0
Math            0
Physics         0
Chemistry       0
English         0
Biology         0
Attendance      0
Study_Hours     0
dtype: int64

In [16]:
std[['Math','Physics']]

     Math  Physics
0      39       38
1      93       97
2      71       81
3      94       86
4      87       67
..    ...      ...
495    73       76
496    66       58
497    47       59
498    77       94
499    87      100

[500 rows x 2 columns]

In [17]:
#Display only the Math column.
std['Math']

0      39
1      93
2      71
3      94
4      87
       ..
495    73
496    66
497    47
498    77
499    87
Name: Math, Length: 500, dtype: int64

In [18]:
#Display only the Attendance column.
std['Attendance']

0      75
1      94
2      85
3      89
4      79
       ..
495    96
496    81
497    76
498    94
499    97
Name: Attendance, Length: 500, dtype: int64

In [19]:
#Display Student_Name and Department.
std[['Student_Name','Department']]

     Student_Name  Department
0    Sneha Sharma     AI & ML
1      Varun Iyer  Mechanical
2     Rahul Patel         ECE
3     Harsha Iyer         CSE
4     Harsha Iyer         CSE
..            ...         ...
495     Kiran Rao     AI & ML
496   Priya Reddy         CSE
497   Rohit Gupta         EEE
498   Akhil Naidu     AI & ML
499     Sai Naidu         CSE

[500 rows x 2 columns]

In [20]:
#Display Math, Physics, Chemistry.
std[['Math','Physics','Chemistry']]

     Math  Physics  Chemistry
0      39       38         40
1      93       97         87
2      71       81         72
3      94       86        100
4      87       67         87
..    ...      ...        ...
495    73       76         72
496    66       58         56
497    47       59         58
498    77       94        100
499    87      100         78

[500 rows x 3 columns]

In [21]:
#Display Student_ID, Student_Name, Attendance.
std[['Student_ID','Student_Name','Attendance']]

    Student_ID  Student_Name  Attendance
0        ST001  Sneha Sharma          75
1        ST002    Varun Iyer          94
2        ST003   Rahul Patel          85
3        ST004   Harsha Iyer          89
4        ST005   Harsha Iyer          79
..         ...           ...         ...
495      ST496     Kiran Rao          96
496      ST497   Priya Reddy          81
497      ST498   Rohit Gupta          76
498      ST499   Akhil Naidu          94
499      ST500     Sai Naidu          97

[500 rows x 3 columns]

In [22]:
type(std['English'])

pandas.core.series.Series

In [23]:
std[['English']]

     English
0         44
1        100
2         80
3         97
4         63
..       ...
495       87
496       57
497       60
498       93
499       82

[500 rows x 1 columns]

In [24]:
#Display Gender, Department, Year.
std[['Gender','Department','Year']]

     Gender  Department  Year
0    Female     AI & ML     2
1      Male  Mechanical     2
2    Female         ECE     3
3    Female         CSE     4
4      Male         CSE     1
..      ...         ...   ...
495    Male     AI & ML     1
496  Female         CSE     1
497    Male         EEE     2
498    Male     AI & ML     2
499  Female         CSE     1

[500 rows x 3 columns]

In [25]:
#Display all subject columns only.
std.columns

Index(['Student_ID', 'Student_Name', 'Gender', 'Department', 'Year', 'Section',
       'Age', 'Math', 'Physics', 'Chemistry', 'English', 'Biology',
       'Attendance', 'Study_Hours'],
      dtype='object')

In [26]:
std[['Math','Physics','Chemistry','English','Biology']]

     Math  Physics  Chemistry  English  Biology
0      39       38         40       44       45
1      93       97         87      100      100
2      71       81         72       80       96
3      94       86        100       97       96
4      87       67         87       63       72
..    ...      ...        ...      ...      ...
495    73       76         72       87      100
496    66       58         56       57       73
497    47       59         58       60       62
498    77       94        100       93       82
499    87      100         78       82       97

[500 rows x 5 columns]

In [149]:
std.iloc[0:9]['Student_Name']

0    Sneha Sharma
1      Varun Iyer
2     Rahul Patel
3     Harsha Iyer
4     Harsha Iyer
5    Vikram Naidu
6     Divya Patel
7     Priya Singh
8     Akhil Patel
Name: Student_Name, dtype: object

In [28]:
std.loc[0:9]['Student_Name']

0    Sneha Sharma
1      Varun Iyer
2     Rahul Patel
3     Harsha Iyer
4     Harsha Iyer
5    Vikram Naidu
6     Divya Patel
7     Priya Singh
8     Akhil Patel
9     Kiran Gupta
Name: Student_Name, dtype: object

Filtering Data

In [29]:
#Display all students who scored more than 90 in Math.
std[std['Math'] > 90]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93,97,87,100,100,94,7
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
8,ST009,Akhil Patel,Female,AI & ML,2,C,22,92,82,76,75,71,90,5
14,ST015,Rohit Gupta,Male,ECE,4,C,20,100,91,95,95,90,100,8
17,ST018,Rohit Reddy,Male,EEE,3,B,21,100,100,100,88,86,93,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468,ST469,Akhil Kumar,Female,EEE,1,C,21,91,100,95,90,91,94,6
476,ST477,Vikram Sharma,Female,EEE,4,C,18,93,100,100,100,100,99,8
482,ST483,Aditya Iyer,Female,AI & ML,4,C,21,100,100,94,100,96,97,8
485,ST486,Sai Singh,Female,Mechanical,1,A,19,100,92,86,100,86,92,6
486,ST487,Priya Patel,Female,AI & ML,4,C,20,100,100,89,100,100,100,8

In [30]:
#Display all students whose attendance is below 75.#
std[std['Attendance'] < 75]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
15,ST016,Sai Sharma,Male,Mechanical,2,A,18,35,56,35,55,38,64,1
21,ST022,Keerthi Patel,Male,ECE,2,A,22,35,35,47,44,45,67,1
22,ST023,Varun Patel,Male,Mechanical,1,A,18,48,39,66,64,54,69,2
24,ST025,Vikram Verma,Male,ECE,4,B,18,49,48,35,35,47,71,1
29,ST030,Pooja Gupta,Male,CSE,1,C,19,47,46,35,42,35,68,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,ST489,Sai Verma,Male,Mechanical,4,A,22,59,64,47,59,38,71,2
490,ST491,Priya Kumar,Male,EEE,1,B,22,54,73,59,67,71,73,3
491,ST492,Varun Rao,Female,AI & ML,1,C,19,65,63,73,78,67,73,4
492,ST493,Sneha Sharma,Female,CSE,1,B,21,43,51,48,50,36,60,1
494,ST495,Sneha Rao,Male,AI & ML,3,A,18,53,47,53,46,44,68,2

In [31]:
#Display all Female students.
std[std['Gender'] == 'Female']

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
0,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39,38,40,44,45,75,2
2,ST003,Rahul Patel,Female,ECE,3,A,19,71,81,72,80,96,85,6
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
5,ST006,Vikram Naidu,Female,AI & ML,3,B,19,79,80,65,77,83,79,5
6,ST007,Divya Patel,Female,EEE,3,C,22,80,78,78,55,61,82,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
491,ST492,Varun Rao,Female,AI & ML,1,C,19,65,63,73,78,67,73,4
492,ST493,Sneha Sharma,Female,CSE,1,B,21,43,51,48,50,36,60,1
493,ST494,Rahul Iyer,Female,AI & ML,3,A,19,79,72,86,76,83,85,5
496,ST497,Priya Reddy,Female,CSE,1,B,21,66,58,56,57,73,81,3
499,ST500,Sai Naidu,Female,CSE,1,B,18,87,100,78,82,97,97,6

In [32]:
#Display all students from the CSE department.
std[std['Department'] == 'CSE']

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
4,ST005,Harsha Iyer,Male,CSE,1,C,19,87,67,87,63,72,79,5
9,ST010,Kiran Gupta,Female,CSE,1,A,19,66,49,59,59,66,80,3
13,ST014,Arjun Reddy,Female,CSE,2,A,21,61,72,64,58,75,75,3
19,ST020,Arjun Naidu,Male,CSE,1,A,19,62,62,53,74,59,80,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,ST482,Rohit Iyer,Male,CSE,1,B,22,83,91,74,72,80,90,5
483,ST484,Rohit Sharma,Male,CSE,4,C,18,68,56,65,66,72,85,4
492,ST493,Sneha Sharma,Female,CSE,1,B,21,43,51,48,50,36,60,1
496,ST497,Priya Reddy,Female,CSE,1,B,21,66,58,56,57,73,81,3
499,ST500,Sai Naidu,Female,CSE,1,B,18,87,100,78,82,97,97,6

In [33]:
#Display students whose Physics marks are greater than 85.
std[std['Physics'] > 85]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93,97,87,100,100,94,7
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
14,ST015,Rohit Gupta,Male,ECE,4,C,20,100,91,95,95,90,100,8
17,ST018,Rohit Reddy,Male,EEE,3,B,21,100,100,100,88,86,93,8
18,ST019,Nikhil Singh,Male,AI & ML,2,A,22,99,91,94,100,93,96,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482,ST483,Aditya Iyer,Female,AI & ML,4,C,21,100,100,94,100,96,97,8
485,ST486,Sai Singh,Female,Mechanical,1,A,19,100,92,86,100,86,92,6
486,ST487,Priya Patel,Female,AI & ML,4,C,20,100,100,89,100,100,100,8
498,ST499,Akhil Naidu,Male,AI & ML,2,C,20,77,94,100,93,82,94,6
499,ST500,Sai Naidu,Female,CSE,1,B,18,87,100,78,82,97,97,6

In [34]:
#Display students whose Math marks are less than 50.
std[std['Math'] < 50]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
0,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39,38,40,44,45,75,2
15,ST016,Sai Sharma,Male,Mechanical,2,A,18,35,56,35,55,38,64,1
21,ST022,Keerthi Patel,Male,ECE,2,A,22,35,35,47,44,45,67,1
22,ST023,Varun Patel,Male,Mechanical,1,A,18,48,39,66,64,54,69,2
24,ST025,Vikram Verma,Male,ECE,4,B,18,49,48,35,35,47,71,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
464,ST465,Pooja Rao,Female,ECE,2,A,18,44,68,63,63,52,72,3
469,ST470,Aisha Gupta,Male,Mechanical,1,B,21,44,45,40,51,35,64,1
478,ST479,Harsha Sharma,Male,CSE,3,B,18,40,35,35,48,36,60,1
492,ST493,Sneha Sharma,Female,CSE,1,B,21,43,51,48,50,36,60,1
497,ST498,Rohit Gupta,Male,EEE,2,A,21,47,59,58,60,62,76,2

In [35]:
#Display students who belong to Section A.
std[std['Section'] == 'A']

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
0,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39,38,40,44,45,75,2
2,ST003,Rahul Patel,Female,ECE,3,A,19,71,81,72,80,96,85,6
7,ST008,Priya Singh,Female,ECE,1,A,22,90,85,82,98,99,88,6
9,ST010,Kiran Gupta,Female,CSE,1,A,19,66,49,59,59,66,80,3
12,ST013,Varun Sharma,Female,EEE,1,A,20,63,69,90,80,92,84,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,ST488,Neha Iyer,Female,Mechanical,1,A,22,73,75,79,97,71,93,6
488,ST489,Sai Verma,Male,Mechanical,4,A,22,59,64,47,59,38,71,2
493,ST494,Rahul Iyer,Female,AI & ML,3,A,19,79,72,86,76,83,85,5
494,ST495,Sneha Rao,Male,AI & ML,3,A,18,53,47,53,46,44,68,2
497,ST498,Rohit Gupta,Male,EEE,2,A,21,47,59,58,60,62,76,2

In [36]:
#Display students studying in Year 4.
std[std['Year'] == 4]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
14,ST015,Rohit Gupta,Male,ECE,4,C,20,100,91,95,95,90,100,8
16,ST017,Arjun Gupta,Male,ECE,4,A,22,54,72,62,72,60,82,3
20,ST021,Priya Patel,Female,CSE,4,B,21,86,94,87,89,81,90,5
24,ST025,Vikram Verma,Male,ECE,4,B,18,49,48,35,35,47,71,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,ST481,Pooja Gupta,Male,ECE,4,A,18,79,76,79,69,85,87,5
482,ST483,Aditya Iyer,Female,AI & ML,4,C,21,100,100,94,100,96,97,8
483,ST484,Rohit Sharma,Male,CSE,4,C,18,68,56,65,66,72,85,4
486,ST487,Priya Patel,Female,AI & ML,4,C,20,100,100,89,100,100,100,8
488,ST489,Sai Verma,Male,Mechanical,4,A,22,59,64,47,59,38,71,2

In [37]:
#Display students whose English marks are greater than 95.
std[std['English'] > 95]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93,97,87,100,100,94,7
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
7,ST008,Priya Singh,Female,ECE,1,A,22,90,85,82,98,99,88,6
18,ST019,Nikhil Singh,Male,AI & ML,2,A,22,99,91,94,100,93,96,8
38,ST039,Neha Kumar,Female,Mechanical,3,B,21,100,100,100,100,100,98,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,ST477,Vikram Sharma,Female,EEE,4,C,18,93,100,100,100,100,99,8
482,ST483,Aditya Iyer,Female,AI & ML,4,C,21,100,100,94,100,96,97,8
485,ST486,Sai Singh,Female,Mechanical,1,A,19,100,92,86,100,86,92,6
486,ST487,Priya Patel,Female,AI & ML,4,C,20,100,100,89,100,100,100,8
487,ST488,Neha Iyer,Female,Mechanical,1,A,22,73,75,79,97,71,93,6

In [38]:
#Display students who satisfy both:
#Math > 80
#Physics > 80
std[(std['Math'] > 80) & (std['Physics'] > 80)]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93,97,87,100,100,94,7
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
7,ST008,Priya Singh,Female,ECE,1,A,22,90,85,82,98,99,88,6
8,ST009,Akhil Patel,Female,AI & ML,2,C,22,92,82,76,75,71,90,5
14,ST015,Rohit Gupta,Male,ECE,4,C,20,100,91,95,95,90,100,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,ST482,Rohit Iyer,Male,CSE,1,B,22,83,91,74,72,80,90,5
482,ST483,Aditya Iyer,Female,AI & ML,4,C,21,100,100,94,100,96,97,8
485,ST486,Sai Singh,Female,Mechanical,1,A,19,100,92,86,100,86,92,6
486,ST487,Priya Patel,Female,AI & ML,4,C,20,100,100,89,100,100,100,8
499,ST500,Sai Naidu,Female,CSE,1,B,18,87,100,78,82,97,97,6

Multiple conditons and filtering

In [39]:
#Show all Female students from the CSE department.
std[(std['Gender'] == 'Female') & (std['Department'] == 'CSE')]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
9,ST010,Kiran Gupta,Female,CSE,1,A,19,66,49,59,59,66,80,3
13,ST014,Arjun Reddy,Female,CSE,2,A,21,61,72,64,58,75,75,3
20,ST021,Priya Patel,Female,CSE,4,B,21,86,94,87,89,81,90,5
30,ST031,Priya Rao,Female,CSE,3,A,19,61,54,65,64,50,73,2
36,ST037,Rohit Singh,Female,CSE,3,C,20,53,46,58,50,47,71,2
69,ST070,Aisha Naidu,Female,CSE,1,B,20,62,67,90,81,86,77,5
91,ST092,Divya Verma,Female,CSE,4,A,20,49,59,61,59,46,76,2
92,ST093,Aditya Verma,Female,CSE,2,B,18,90,72,90,96,84,89,6
101,ST102,Varun Rao,Female,CSE,1,B,21,93,100,100,92,80,90,7
107,ST108,Harsha Gupta,Female,CSE,3,C,19,96,100,98,100,99,87,7
112,ST113,Keerthi Gupta,Female,CSE,2,B,22,35,36,57,35,51,60,1
114,ST115,Varun Gupta,Female,CSE,4,C,18,91,100,79,100,87,87,7
116,ST117,Harsha Reddy,Female,CSE,2,B,22,83,93,100,90,100,100,7
132,ST133,Varun Reddy,Female,CSE,2,B,21,49,77,76,54,73,80,3
137,ST138,Kiran Rao,Female,CSE,3,A,22,99,99,80,94,89,92,7
142,ST143,Priya Singh,Female,CSE,3,B,21,98,93,100,100,100,100,8
143,ST144,Harsha Gupta,Female,CSE,4,A,21,55,48,47,55,66,76,3
145,ST146,Meghana Verma,Female,CSE,1,C,21,98,96,94,78,100,98,6
146,ST147,Rahul Patel,Female,CSE,2,A,19,83,100,89,72,90,93,6
151,ST152,Kiran Kumar,Female,CSE,3,C,22,97,89,76,91,100,96,6
157,ST158,Nikhil Rao,Female,CSE,1,A,21,95,87,91,100,85,100,7
167,ST168,Sneha Verma,Female,CSE,4,B,22,69,66,56,67,71,73,4
169,ST170,Rohit Verma,Female,CSE,2,C,19,89,85,83,100,78,97,6
185,ST186,Arjun Gupta,Female,CSE,4,A,22,99,82,98,95,100,100,7
187,ST188,Priya Reddy,Female,CSE,3,B,19,58,75,59,61,74,80,3
208,ST209,Aditya Naidu,Female,CSE,1,C,20,56,54,37,35,57,62,1
210,ST211,Kiran Reddy,Female,CSE,1,B,19,56,61,56,67,56,72,2
213,ST214,Nikhil Singh,Female,CSE,1,A,20,100,96,91,92,90,100,8
229,ST230,Ananya Verma,Female,CSE,2,B,22,80,100,86,86,88,99,7
241,ST242,Sneha Patel,Female,CSE,3,C,19,49,67,55,71,52,74,3
249,ST250,Arjun Kumar,Female,CSE,1,A,20,75,83,95,97,95,91,6
252,ST253,Kiran Kumar,Female,CSE,2,C,22,87,87,81,88,69,77,5
256,ST257,Pooja Verma,Female,CSE,2,B,18,76,89,66,85,64,79,5
300,ST301,Rahul Iyer,Female,CSE,4,A,19,53,59,38,60,44,65,2
307,ST308,Harsha Naidu,Female,CSE,1,A,20,93,100,100,100,100,100,8
315,ST316,Aisha Patel,Female,CSE,4,A,20,66,48,53,57,53,77,3
321,ST322,Aisha Kumar,Female,CSE,3,C,19,47,50,35,35,49,60,1
332,ST333,Akhil Iyer,Female,CSE,3,B,19,50,68,52,46,64,74,2
341,ST342,Keerthi Singh,Female,CSE,1,C,19,40,55,49,59,54,67,1
342,ST343,Neha Gupta,Female,CSE,1,A,21,50,55,66,53,53,80,3
348,ST349,Ananya Gupta,Female,CSE,3,C,21,100,100,92,100,79,96,7
368,ST369,Aisha Reddy,Female,CSE,3,A,19,99,92,100,100,95,100,8
438,ST439,Nikhil Naidu,Female,CSE,3,A,22,63,63,40,54,49,62,2
441,ST442,Ananya Gupta,Female,CSE,3,C,21,83,100,83,95,90,90,7
446,ST447,Divya Rao,Female,CSE,4,C,19,62,52,42,52,63,72,2
447,ST448,Aditya Reddy,Female,CSE,4,A,18,99,97,84,84,100,93,6
455,ST456,Neha Naidu,Female,CSE,3,A,22,70,69,77,61,70,78,4
460,ST461,Neha Kumar,Female,CSE,3,B,18,66,72,90,74,83,84,5
463,ST464,Aditya Patel,Female,CSE,1,A,20,67,53,71,56,73,67,3
492,ST493,Sneha Sharma,Female,CSE,1,B,21,43,51,48,50,36,60,1
496,ST497,Priya Reddy,Female,CSE,1,B,21,66,58,56,57,73,81,3
499,ST500,Sai Naidu,Female,CSE,1,B,18,87,100,78,82,97,97,6

In [40]:
#Show all students with:
#Math > 80
#Attendance > 90
std[(std['Math'] > 80) & (std['Attendance'] > 90)]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93,97,87,100,100,94,7
14,ST015,Rohit Gupta,Male,ECE,4,C,20,100,91,95,95,90,100,8
17,ST018,Rohit Reddy,Male,EEE,3,B,21,100,100,100,88,86,93,8
18,ST019,Nikhil Singh,Male,AI & ML,2,A,22,99,91,94,100,93,96,8
38,ST039,Neha Kumar,Female,Mechanical,3,B,21,100,100,100,100,100,98,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482,ST483,Aditya Iyer,Female,AI & ML,4,C,21,100,100,94,100,96,97,8
484,ST485,Rohit Sharma,Male,ECE,3,A,20,81,74,88,64,67,93,5
485,ST486,Sai Singh,Female,Mechanical,1,A,19,100,92,86,100,86,92,6
486,ST487,Priya Patel,Female,AI & ML,4,C,20,100,100,89,100,100,100,8
499,ST500,Sai Naidu,Female,CSE,1,B,18,87,100,78,82,97,97,6

In [41]:
#Show all students from Year 3 who belong to Section B.
std[(std['Year'] == 3) & (std['Section'] == 'B')]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
5,ST006,Vikram Naidu,Female,AI & ML,3,B,19,79,80,65,77,83,79,5
17,ST018,Rohit Reddy,Male,EEE,3,B,21,100,100,100,88,86,93,8
38,ST039,Neha Kumar,Female,Mechanical,3,B,21,100,100,100,100,100,98,8
42,ST043,Akhil Patel,Female,Mechanical,3,B,22,100,86,100,100,96,100,7
59,ST060,Harsha Naidu,Female,EEE,3,B,21,70,69,65,85,68,86,5
62,ST063,Kiran Naidu,Male,CSE,3,B,21,93,100,89,96,100,100,8
68,ST069,Priya Patel,Female,Mechanical,3,B,18,100,100,100,96,100,100,8
81,ST082,Pooja Patel,Male,EEE,3,B,22,100,87,100,98,100,89,7
90,ST091,Varun Gupta,Female,AI & ML,3,B,20,83,99,71,73,93,85,6
104,ST105,Sneha Singh,Female,ECE,3,B,19,88,100,88,88,99,94,8
106,ST107,Pooja Sharma,Female,Mechanical,3,B,18,73,67,59,79,55,76,4
108,ST109,Vikram Sharma,Male,ECE,3,B,20,54,35,45,48,39,62,1
123,ST124,Meghana Patel,Female,ECE,3,B,21,93,88,88,78,70,83,6
142,ST143,Priya Singh,Female,CSE,3,B,21,98,93,100,100,100,100,8
150,ST151,Sai Singh,Male,Mechanical,3,B,19,62,53,49,52,71,78,3
159,ST160,Divya Patel,Male,CSE,3,B,22,100,100,100,84,100,94,7
180,ST181,Keerthi Singh,Male,CSE,3,B,19,100,98,97,100,100,100,8
187,ST188,Priya Reddy,Female,CSE,3,B,19,58,75,59,61,74,80,3
218,ST219,Meghana Verma,Female,EEE,3,B,22,55,64,75,67,51,76,3
219,ST220,Keerthi Singh,Male,EEE,3,B,21,66,62,80,79,66,82,4
278,ST279,Aisha Naidu,Female,Mechanical,3,B,20,53,62,50,43,71,67,3
287,ST288,Harsha Singh,Male,CSE,3,B,18,68,83,63,72,69,83,5
332,ST333,Akhil Iyer,Female,CSE,3,B,19,50,68,52,46,64,74,2
340,ST341,Neha Gupta,Male,EEE,3,B,18,65,72,79,74,74,86,4
346,ST347,Divya Rao,Female,ECE,3,B,19,66,69,75,70,63,80,3
355,ST356,Kiran Singh,Male,Mechanical,3,B,22,94,91,79,85,76,84,6
358,ST359,Meghana Iyer,Male,CSE,3,B,18,96,100,88,79,100,95,7
369,ST370,Sneha Rao,Male,AI & ML,3,B,21,93,89,75,89,89,91,6
371,ST372,Sai Naidu,Female,EEE,3,B,21,56,55,38,62,44,67,2
378,ST379,Nikhil Singh,Male,Mechanical,3,B,19,100,100,91,95,100,98,7
384,ST385,Ananya Iyer,Female,AI & ML,3,B,22,48,48,40,39,36,69,2
389,ST390,Sneha Patel,Female,Mechanical,3,B,22,99,88,100,92,100,98,7
401,ST402,Sai Reddy,Male,EEE,3,B,19,91,84,82,90,90,82,5
404,ST405,Aditya Rao,Female,AI & ML,3,B,19,59,68,56,58,73,68,3
459,ST460,Rahul Sharma,Male,Mechanical,3,B,21,78,89,99,89,89,92,7
460,ST461,Neha Kumar,Female,CSE,3,B,18,66,72,90,74,83,84,5
470,ST471,Aisha Verma,Male,AI & ML,3,B,21,76,67,75,71,81,86,5
472,ST473,Aisha Patel,Female,EEE,3,B,18,65,75,69,75,53,81,3
478,ST479,Harsha Sharma,Male,CSE,3,B,18,40,35,35,48,36,60,1

In [42]:
#Show all students whose:
#Physics > 85
#Chemistry > 85
#English > 85
std[(std['Physics'] > 85) & (std['Chemistry'] > 85) & (std['English'] > 85)]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93,97,87,100,100,94,7
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
14,ST015,Rohit Gupta,Male,ECE,4,C,20,100,91,95,95,90,100,8
17,ST018,Rohit Reddy,Male,EEE,3,B,21,100,100,100,88,86,93,8
18,ST019,Nikhil Singh,Male,AI & ML,2,A,22,99,91,94,100,93,96,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476,ST477,Vikram Sharma,Female,EEE,4,C,18,93,100,100,100,100,99,8
482,ST483,Aditya Iyer,Female,AI & ML,4,C,21,100,100,94,100,96,97,8
485,ST486,Sai Singh,Female,Mechanical,1,A,19,100,92,86,100,86,92,6
486,ST487,Priya Patel,Female,AI & ML,4,C,20,100,100,89,100,100,100,8
498,ST499,Akhil Naidu,Male,AI & ML,2,C,20,77,94,100,93,82,94,6

In [43]:
#Show all Male students whose attendance is below 70.
std[(std['Gender'] == 'Male') & (std['Attendance'] < 70)]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
15,ST016,Sai Sharma,Male,Mechanical,2,A,18,35,56,35,55,38,64,1
21,ST022,Keerthi Patel,Male,ECE,2,A,22,35,35,47,44,45,67,1
22,ST023,Varun Patel,Male,Mechanical,1,A,18,48,39,66,64,54,69,2
29,ST030,Pooja Gupta,Male,CSE,1,C,19,47,46,35,42,35,68,1
45,ST046,Akhil Verma,Male,AI & ML,4,B,22,44,35,59,40,38,69,1
49,ST050,Pooja Rao,Male,EEE,1,C,22,36,49,35,53,59,68,1
63,ST064,Keerthi Reddy,Male,EEE,4,A,22,35,52,45,57,36,61,1
74,ST075,Vikram Gupta,Male,ECE,4,C,21,54,53,59,41,56,62,2
83,ST084,Sneha Naidu,Male,ECE,1,A,20,39,39,41,35,35,66,1
88,ST089,Harsha Kumar,Male,Mechanical,3,C,19,43,59,48,35,52,63,2
108,ST109,Vikram Sharma,Male,ECE,3,B,20,54,35,45,48,39,62,1
110,ST111,Aditya Iyer,Male,CSE,2,A,22,35,41,48,40,42,60,1
118,ST119,Kiran Kumar,Male,AI & ML,3,A,19,48,73,67,63,58,69,3
122,ST123,Priya Naidu,Male,ECE,1,C,19,50,42,42,44,44,64,1
140,ST141,Akhil Naidu,Male,AI & ML,1,C,21,35,35,53,35,56,66,1
176,ST177,Arjun Iyer,Male,Mechanical,1,A,21,69,55,68,58,48,68,3
188,ST189,Nikhil Verma,Male,Mechanical,2,C,20,53,48,52,40,59,67,2
190,ST191,Kiran Rao,Male,CSE,1,C,21,35,35,35,47,35,64,1
197,ST198,Arjun Kumar,Male,EEE,2,B,20,56,35,57,50,35,63,1
202,ST203,Aisha Naidu,Male,Mechanical,1,C,18,58,35,47,38,60,63,2
206,ST207,Nikhil Naidu,Male,AI & ML,3,C,18,39,39,39,44,42,60,1
223,ST224,Aisha Iyer,Male,CSE,2,C,20,61,63,64,63,55,68,3
227,ST228,Akhil Singh,Male,ECE,1,C,18,49,35,50,54,35,67,1
255,ST256,Arjun Sharma,Male,CSE,3,A,18,45,38,49,51,45,69,1
258,ST259,Akhil Iyer,Male,ECE,2,A,18,48,58,73,54,59,67,3
259,ST260,Varun Rao,Male,ECE,2,C,20,44,59,47,42,50,62,2
309,ST310,Rohit Kumar,Male,AI & ML,3,C,21,42,56,35,47,35,60,1
325,ST326,Nikhil Rao,Male,Mechanical,1,C,18,49,35,40,41,39,60,1
334,ST335,Aditya Naidu,Male,Mechanical,4,B,22,42,56,42,35,55,61,1
339,ST340,Sneha Naidu,Male,CSE,4,B,18,52,46,57,46,47,60,1
361,ST362,Pooja Reddy,Male,CSE,4,C,20,35,35,35,52,35,60,1
367,ST368,Ananya Patel,Male,Mechanical,3,A,18,70,67,72,60,57,68,3
374,ST375,Aditya Rao,Male,EEE,1,B,20,55,58,53,47,49,64,1
391,ST392,Nikhil Patel,Male,AI & ML,4,C,19,52,48,61,46,61,68,2
392,ST393,Aisha Iyer,Male,AI & ML,4,C,18,50,64,54,48,37,66,2
395,ST396,Divya Iyer,Male,CSE,3,A,18,51,67,55,54,64,69,3
415,ST416,Divya Rao,Male,AI & ML,2,B,18,64,63,50,52,36,64,2
427,ST428,Nikhil Sharma,Male,AI & ML,4,B,19,41,50,51,35,43,63,1
448,ST449,Sneha Kumar,Male,EEE,1,B,22,46,47,35,39,45,67,1
449,ST450,Divya Patel,Male,EEE,4,C,22,49,45,61,48,40,69,2
456,ST457,Keerthi Iyer,Male,CSE,4,C,22,35,35,37,35,53,65,1
469,ST470,Aisha Gupta,Male,Mechanical,1,B,21,44,45,40,51,35,64,1
471,ST472,Priya Gupta,Male,EEE,4,A,22,60,54,66,64,58,67,2
478,ST479,Harsha Sharma,Male,CSE,3,B,18,40,35,35,48,36,60,1
494,ST495,Sneha Rao,Male,AI & ML,3,A,18,53,47,53,46,44,68,2

In [44]:
#Show all students from either:
#CSE
#AI & ML
std[(std['Department'] == 'CSE') | (std['Department'] == 'AI & ML')]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
0,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39,38,40,44,45,75,2
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
4,ST005,Harsha Iyer,Male,CSE,1,C,19,87,67,87,63,72,79,5
5,ST006,Vikram Naidu,Female,AI & ML,3,B,19,79,80,65,77,83,79,5
8,ST009,Akhil Patel,Female,AI & ML,2,C,22,92,82,76,75,71,90,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,ST495,Sneha Rao,Male,AI & ML,3,A,18,53,47,53,46,44,68,2
495,ST496,Kiran Rao,Male,AI & ML,1,B,22,73,76,72,87,100,96,6
496,ST497,Priya Reddy,Female,CSE,1,B,21,66,58,56,57,73,81,3
498,ST499,Akhil Naidu,Male,AI & ML,2,C,20,77,94,100,93,82,94,6
499,ST500,Sai Naidu,Female,CSE,1,B,18,87,100,78,82,97,97,6

In [45]:
#Show students who scored more than 90 in Math OR Physics.
std[(std['Math'] > 90) | (std['Physics'] > 90)]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93,97,87,100,100,94,7
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
8,ST009,Akhil Patel,Female,AI & ML,2,C,22,92,82,76,75,71,90,5
14,ST015,Rohit Gupta,Male,ECE,4,C,20,100,91,95,95,90,100,8
17,ST018,Rohit Reddy,Male,EEE,3,B,21,100,100,100,88,86,93,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482,ST483,Aditya Iyer,Female,AI & ML,4,C,21,100,100,94,100,96,97,8
485,ST486,Sai Singh,Female,Mechanical,1,A,19,100,92,86,100,86,92,6
486,ST487,Priya Patel,Female,AI & ML,4,C,20,100,100,89,100,100,100,8
498,ST499,Akhil Naidu,Male,AI & ML,2,C,20,77,94,100,93,82,94,6
499,ST500,Sai Naidu,Female,CSE,1,B,18,87,100,78,82,97,97,6

In [46]:
#Show students whose attendance is between 80 and 90.
std[(std['Attendance'] > 80) & (std['Attendance'] < 90)]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
2,ST003,Rahul Patel,Female,ECE,3,A,19,71,81,72,80,96,85,6
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
6,ST007,Divya Patel,Female,EEE,3,C,22,80,78,78,55,61,82,4
7,ST008,Priya Singh,Female,ECE,1,A,22,90,85,82,98,99,88,6
10,ST011,Akhil Gupta,Female,Mechanical,1,C,18,66,72,76,68,77,87,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,ST481,Pooja Gupta,Male,ECE,4,A,18,79,76,79,69,85,87,5
483,ST484,Rohit Sharma,Male,CSE,4,C,18,68,56,65,66,72,85,4
489,ST490,Vikram Verma,Male,EEE,2,B,21,77,70,66,64,72,83,5
493,ST494,Rahul Iyer,Female,AI & ML,3,A,19,79,72,86,76,83,85,5
496,ST497,Priya Reddy,Female,CSE,1,B,21,66,58,56,57,73,81,3

In [47]:
#Show students who are not in the ECE department.
std[std['Department'] != 'ECE']

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
0,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39,38,40,44,45,75,2
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93,97,87,100,100,94,7
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
4,ST005,Harsha Iyer,Male,CSE,1,C,19,87,67,87,63,72,79,5
5,ST006,Vikram Naidu,Female,AI & ML,3,B,19,79,80,65,77,83,79,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ST496,Kiran Rao,Male,AI & ML,1,B,22,73,76,72,87,100,96,6
496,ST497,Priya Reddy,Female,CSE,1,B,21,66,58,56,57,73,81,3
497,ST498,Rohit Gupta,Male,EEE,2,A,21,47,59,58,60,62,76,2
498,ST499,Akhil Naidu,Male,AI & ML,2,C,20,77,94,100,93,82,94,6
499,ST500,Sai Naidu,Female,CSE,1,B,18,87,100,78,82,97,97,6

In [48]:
#Show students who satisfy:
#Department is AI & ML
#Year is 4
#Math > 85
#Attendance > 90
std[(std['Department'] == 'AI & ML') & (std['Year'] == 4) & (std['Math'] > 85) & (std['Attendance'] > 90)]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
79,ST080,Divya Iyer,Female,AI & ML,4,A,20,100,100,100,100,100,100,8
267,ST268,Vikram Reddy,Male,AI & ML,4,C,20,100,89,100,90,100,94,8
320,ST321,Ananya Naidu,Male,AI & ML,4,C,21,100,96,93,81,82,100,7
330,ST331,Arjun Reddy,Female,AI & ML,4,B,20,88,100,90,100,86,93,8
482,ST483,Aditya Iyer,Female,AI & ML,4,C,21,100,100,94,100,96,97,8
486,ST487,Priya Patel,Female,AI & ML,4,C,20,100,100,89,100,100,100,8

Sorting

In [49]:
#Sort students by Math in ascending order.
std.sort_values(by='Math', ascending=True)

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
21,ST022,Keerthi Patel,Male,ECE,2,A,22,35,35,47,44,45,67,1
456,ST457,Keerthi Iyer,Male,CSE,4,C,22,35,35,37,35,53,65,1
63,ST064,Keerthi Reddy,Male,EEE,4,A,22,35,52,45,57,36,61,1
140,ST141,Akhil Naidu,Male,AI & ML,1,C,21,35,35,53,35,56,66,1
361,ST362,Pooja Reddy,Male,CSE,4,C,20,35,35,35,52,35,60,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,ST454,Neha Patel,Female,Mechanical,4,C,19,100,100,92,91,100,93,8
213,ST214,Nikhil Singh,Female,CSE,1,A,20,100,96,91,92,90,100,8
222,ST223,Nikhil Reddy,Female,Mechanical,4,C,21,100,100,88,99,100,88,7
194,ST195,Nikhil Gupta,Female,EEE,4,A,20,100,95,93,85,100,92,7
201,ST202,Keerthi Gupta,Female,ECE,4,C,21,100,100,98,92,91,97,8

In [50]:
#Sort students by Math in descending order.
std.sort_values(by='Math', ascending = False)

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
482,ST483,Aditya Iyer,Female,AI & ML,4,C,21,100,100,94,100,96,97,8
42,ST043,Akhil Patel,Female,Mechanical,3,B,22,100,86,100,100,96,100,7
425,ST426,Divya Reddy,Male,CSE,4,A,20,100,100,94,90,93,96,7
453,ST454,Neha Patel,Female,Mechanical,4,C,19,100,100,92,91,100,93,8
38,ST039,Neha Kumar,Female,Mechanical,3,B,21,100,100,100,100,100,98,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,ST116,Aditya Verma,Female,EEE,3,A,21,35,54,59,48,43,67,1
190,ST191,Kiran Rao,Male,CSE,1,C,21,35,35,35,47,35,64,1
63,ST064,Keerthi Reddy,Male,EEE,4,A,22,35,52,45,57,36,61,1
456,ST457,Keerthi Iyer,Male,CSE,4,C,22,35,35,37,35,53,65,1
21,ST022,Keerthi Patel,Male,ECE,2,A,22,35,35,47,44,45,67,1

In [51]:
#Sort students by Attendance in descending order.
std.sort_values('Attendance',ascending = False)

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
276,ST277,Akhil Patel,Male,Mechanical,2,C,20,100,100,100,89,90,100,8
284,ST285,Aditya Reddy,Female,ECE,3,A,19,100,91,86,100,100,100,7
42,ST043,Akhil Patel,Female,Mechanical,3,B,22,100,86,100,100,96,100,7
314,ST315,Priya Iyer,Male,ECE,2,C,22,100,97,100,93,100,100,8
250,ST251,Kiran Patel,Male,Mechanical,1,C,19,100,94,100,100,92,100,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,ST362,Pooja Reddy,Male,CSE,4,C,20,35,35,35,52,35,60,1
161,ST162,Nikhil Gupta,Female,AI & ML,2,C,20,36,42,46,55,53,60,1
112,ST113,Keerthi Gupta,Female,CSE,2,B,22,35,36,57,35,51,60,1
47,ST048,Nikhil Patel,Female,AI & ML,1,B,22,47,40,35,54,41,60,1
478,ST479,Harsha Sharma,Male,CSE,3,B,18,40,35,35,48,36,60,1

In [52]:
#Display the Top 10 students based on Math marks.
std.sort_values('Math', ascending=False).head(10)

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
482,ST483,Aditya Iyer,Female,AI & ML,4,C,21,100,100,94,100,96,97,8
42,ST043,Akhil Patel,Female,Mechanical,3,B,22,100,86,100,100,96,100,7
425,ST426,Divya Reddy,Male,CSE,4,A,20,100,100,94,90,93,96,7
453,ST454,Neha Patel,Female,Mechanical,4,C,19,100,100,92,91,100,93,8
38,ST039,Neha Kumar,Female,Mechanical,3,B,21,100,100,100,100,100,98,8
41,ST042,Rahul Reddy,Female,AI & ML,2,C,22,100,92,100,100,88,93,8
386,ST387,Kiran Iyer,Male,EEE,4,B,18,100,100,94,100,100,94,7
378,ST379,Nikhil Singh,Male,Mechanical,3,B,19,100,100,91,95,100,98,7
380,ST381,Ananya Patel,Female,Mechanical,1,C,19,100,83,95,100,95,97,7
382,ST383,Aditya Patel,Male,AI & ML,3,A,22,100,100,100,98,100,87,7

In [53]:
#Display the Bottom 10 students based on Math marks.
std.sort_values('Math', ascending = False).tail(10)

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
140,ST141,Akhil Naidu,Male,AI & ML,1,C,21,35,35,53,35,56,66,1
110,ST111,Aditya Iyer,Male,CSE,2,A,22,35,41,48,40,42,60,1
397,ST398,Harsha Singh,Female,AI & ML,2,B,21,35,41,44,35,45,65,1
361,ST362,Pooja Reddy,Male,CSE,4,C,20,35,35,35,52,35,60,1
112,ST113,Keerthi Gupta,Female,CSE,2,B,22,35,36,57,35,51,60,1
115,ST116,Aditya Verma,Female,EEE,3,A,21,35,54,59,48,43,67,1
190,ST191,Kiran Rao,Male,CSE,1,C,21,35,35,35,47,35,64,1
63,ST064,Keerthi Reddy,Male,EEE,4,A,22,35,52,45,57,36,61,1
456,ST457,Keerthi Iyer,Male,CSE,4,C,22,35,35,37,35,53,65,1
21,ST022,Keerthi Patel,Male,ECE,2,A,22,35,35,47,44,45,67,1

In [54]:
#Sort students by Physics in descending order.
std.sort_values('Physics', ascending = False)

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
17,ST018,Rohit Reddy,Male,EEE,3,B,21,100,100,100,88,86,93,8
499,ST500,Sai Naidu,Female,CSE,1,B,18,87,100,78,82,97,97,6
305,ST306,Harsha Sharma,Male,CSE,3,C,22,100,100,94,100,96,91,7
307,ST308,Harsha Naidu,Female,CSE,1,A,20,93,100,100,100,100,100,8
35,ST036,Sai Verma,Male,EEE,2,B,18,93,100,100,94,98,87,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,ST109,Vikram Sharma,Male,ECE,3,B,20,54,35,45,48,39,62,1
45,ST046,Akhil Verma,Male,AI & ML,4,B,22,44,35,59,40,38,69,1
456,ST457,Keerthi Iyer,Male,CSE,4,C,22,35,35,37,35,53,65,1
21,ST022,Keerthi Patel,Male,ECE,2,A,22,35,35,47,44,45,67,1
478,ST479,Harsha Sharma,Male,CSE,3,B,18,40,35,35,48,36,60,1

In [55]:
#Sort students first by Department (A–Z), then by Math (highest first within each department).
std.sort_values(by= ['Department','Math'],ascending =[True, False])

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
41,ST042,Rahul Reddy,Female,AI & ML,2,C,22,100,92,100,100,88,93,8
79,ST080,Divya Iyer,Female,AI & ML,4,A,20,100,100,100,100,100,100,8
125,ST126,Harsha Rao,Female,AI & ML,1,B,22,100,84,100,100,100,97,7
131,ST132,Varun Verma,Male,AI & ML,2,B,18,100,100,91,100,100,100,8
134,ST135,Sai Reddy,Female,AI & ML,2,A,20,100,100,100,100,100,96,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,ST290,Nikhil Reddy,Female,Mechanical,2,A,21,43,35,44,42,64,63,2
291,ST292,Rahul Verma,Male,Mechanical,4,A,18,43,43,50,59,54,72,2
334,ST335,Aditya Naidu,Male,Mechanical,4,B,22,42,56,42,35,55,61,1
458,ST459,Nikhil Kumar,Female,Mechanical,1,B,21,42,52,66,50,53,67,2
15,ST016,Sai Sharma,Male,Mechanical,2,A,18,35,56,35,55,38,64,1

In [56]:
#Show the Top 5 students with the highest attendance.
std.sort_values('Attendance', ascending = False).head(5)

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
276,ST277,Akhil Patel,Male,Mechanical,2,C,20,100,100,100,89,90,100,8
284,ST285,Aditya Reddy,Female,ECE,3,A,19,100,91,86,100,100,100,7
42,ST043,Akhil Patel,Female,Mechanical,3,B,22,100,86,100,100,96,100,7
314,ST315,Priya Iyer,Male,ECE,2,C,22,100,97,100,93,100,100,8
250,ST251,Kiran Patel,Male,Mechanical,1,C,19,100,94,100,100,92,100,8

In [57]:
#Show the Top 20 students based on English marks.
std.sort_values('English', ascending = False).head(20)

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
348,ST349,Ananya Gupta,Female,CSE,3,C,21,100,100,92,100,79,96,7
351,ST352,Aisha Kumar,Female,AI & ML,3,C,18,93,100,100,100,90,99,7
42,ST043,Akhil Patel,Female,Mechanical,3,B,22,100,86,100,100,96,100,7
46,ST047,Nikhil Verma,Male,EEE,2,B,21,97,95,100,100,100,92,8
76,ST077,Keerthi Rao,Female,EEE,4,B,19,98,92,100,100,100,96,8
330,ST331,Arjun Reddy,Female,AI & ML,4,B,20,88,100,90,100,86,93,8
336,ST337,Divya Singh,Male,EEE,2,B,20,100,100,95,100,97,91,7
338,ST339,Varun Kumar,Female,EEE,2,A,21,90,100,100,100,98,100,8
316,ST317,Neha Verma,Female,ECE,3,C,20,100,87,100,100,100,95,8
307,ST308,Harsha Naidu,Female,CSE,1,A,20,93,100,100,100,100,100,8
317,ST318,Aditya Iyer,Male,EEE,2,C,18,90,94,82,100,100,100,7
296,ST297,Arjun Singh,Female,Mechanical,2,C,18,94,100,98,100,100,100,7
368,ST369,Aisha Reddy,Female,CSE,3,A,19,99,92,100,100,95,100,8
305,ST306,Harsha Sharma,Male,CSE,3,C,22,100,100,94,100,96,91,7
360,ST361,Aisha Gupta,Male,CSE,2,C,19,84,95,100,100,100,90,7
362,ST363,Aisha Reddy,Male,ECE,4,B,21,91,81,93,100,84,100,7
364,ST365,Meghana Reddy,Female,EEE,4,B,18,100,94,91,100,99,97,8
284,ST285,Aditya Reddy,Female,ECE,3,A,19,100,91,86,100,100,100,7
66,ST067,Ananya Gupta,Male,AI & ML,1,B,21,89,95,97,100,97,100,8
38,ST039,Neha Kumar,Female,Mechanical,3,B,21,100,100,100,100,100,98,8

In [58]:
#Show the Top 10 AI & ML students based on Math marks.
std[std['Department'] == 'AI & ML'].sort_values(by='Math', ascending=False).head(10)

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
125,ST126,Harsha Rao,Female,AI & ML,1,B,22,100,84,100,100,100,97,7
131,ST132,Varun Verma,Male,AI & ML,2,B,18,100,100,91,100,100,100,8
134,ST135,Sai Reddy,Female,AI & ML,2,A,20,100,100,100,100,100,96,8
149,ST150,Meghana Rao,Female,AI & ML,1,A,18,100,100,100,89,100,97,8
178,ST179,Varun Naidu,Female,AI & ML,1,B,19,100,93,88,100,98,100,8
160,ST161,Sai Iyer,Female,AI & ML,2,B,22,100,97,100,88,90,100,8
79,ST080,Divya Iyer,Female,AI & ML,4,A,20,100,100,100,100,100,100,8
41,ST042,Rahul Reddy,Female,AI & ML,2,C,22,100,92,100,100,88,93,8
382,ST383,Aditya Patel,Male,AI & ML,3,A,22,100,100,100,98,100,87,7
418,ST419,Vikram Gupta,Female,AI & ML,2,C,22,100,100,100,100,97,100,8

groupby()

In [59]:
std.groupby('Department')

In [60]:
std.groupby('Department')['Math'].mean()

Department
AI & ML       72.653846
CSE           71.230000
ECE           72.845361
EEE           73.052632
Mechanical    76.067308
Name: Math, dtype: float64

In [61]:
#Find the average Physics marks for each department.
std.groupby('Department')['Physics'].mean()

Department
AI & ML       73.278846
CSE           73.820000
ECE           73.659794
EEE           74.852632
Mechanical    76.471154
Name: Physics, dtype: float64

In [62]:
#Find the average Attendance for each department.
std.groupby('Department')['Attendance'].mean()

Department
AI & ML       82.365385
CSE           82.210000
ECE           83.164948
EEE           82.989474
Mechanical    83.923077
Name: Attendance, dtype: float64

In [63]:
#Find the highest Math marks in each department.
std.groupby('Department')['Math'].max()

Department
AI & ML       100
CSE           100
ECE           100
EEE           100
Mechanical    100
Name: Math, dtype: int64

In [64]:
#Find the lowest English marks in each department.
std.groupby('Department')['English'].min()

Department
AI & ML       35
CSE           35
ECE           35
EEE           37
Mechanical    35
Name: English, dtype: int64

In [65]:
#Count how many students are in each department.
std.groupby('Department')['Student_ID'].count()

Department
AI & ML       104
CSE           100
ECE            97
EEE            95
Mechanical    104
Name: Student_ID, dtype: int64

In [66]:
#Find the total Math marks scored by each department.
std.groupby('Department')['Math'].sum()

Department
AI & ML       7556
CSE           7123
ECE           7066
EEE           6940
Mechanical    7911
Name: Math, dtype: int64

In [67]:
#Find the average Study Hours for each department.
std.groupby('Department')['Study_Hours'].mean()

Department
AI & ML       4.605769
CSE           4.440000
ECE           4.628866
EEE           4.589474
Mechanical    4.942308
Name: Study_Hours, dtype: float64

In [68]:
#Which department has the highest average Biology marks?
biology_avg = std.groupby('Department')['Biology'].mean()
print(biology_avg)
print(biology_avg.idxmax())

Department
AI & ML       72.173077
CSE           73.210000
ECE           72.268041
EEE           73.431579
Mechanical    76.009615
Name: Biology, dtype: float64
Mechanical

In [69]:
#Which department has the lowest average Attendance?
std.groupby('Department')['Attendance'].mean().idxmin()

'CSE'

In [70]:
std.groupby('Department')[['Math','Physics','Chemistry','English','Biology']].mean()

                 Math    Physics  Chemistry    English    Biology
Department
AI & ML     72.653846  73.278846  72.932692  72.596154  72.173077
CSE         71.230000  73.820000  71.300000  72.780000  73.210000
ECE         72.845361  73.659794  73.103093  73.350515  72.268041
EEE         73.052632  74.852632  73.031579  74.147368  73.431579
Mechanical  76.067308  76.471154  75.019231  76.384615  76.009615

In [71]:
#For each department, display:
#Mean
#Maximum
#Minimum
#of Physics.
std.groupby('Department')['Physics'].agg(['mean','max','min'])

                 mean  max  min
Department
AI & ML     73.278846  100   35
CSE         73.820000  100   35
ECE         73.659794  100   35
EEE         74.852632  100   35
Mechanical  76.471154  100   35

In [72]:
#For each department, display:
#Mean
#Sum
#of Attendance.
std.groupby('Department')['Attendance'].agg(['mean','sum'])

                 mean   sum
Department
AI & ML     82.365385  8566
CSE         82.210000  8221
ECE         83.164948  8067
EEE         82.989474  7884
Mechanical  83.923077  8728

In [73]:
#For each department, display:
#Count
#Mean
#Max
#of Study_Hours.
std.groupby('Department')['Study_Hours'].agg(['count','mean','max'])

            count      mean  max
Department
AI & ML       104  4.605769    8
CSE           100  4.440000    8
ECE            97  4.628866    8
EEE            95  4.589474    8
Mechanical    104  4.942308    8

In [74]:
#For each department, display:
#Mean
#Max
#Min
#of Math and Physics together.
std.groupby('Department')[['Math','Physics']].agg(['mean','max','min'])

                 Math             Physics
                 mean  max min       mean  max min
Department
AI & ML     72.653846  100  35  73.278846  100  35
CSE         71.230000  100  35  73.820000  100  35
ECE         72.845361  100  35  73.659794  100  35
EEE         73.052632  100  35  74.852632  100  35
Mechanical  76.067308  100  35  76.471154  100  35

In [75]:
#Create one summary table for each department containing:

#Math → Mean, Max
#Physics → Mean, Max
#Attendance → Mean

std.groupby('Department').agg(
    Math_Mean=('Math', 'mean'),
    Math_Max=('Math', 'max'),
    Physics_Mean=('Physics', 'mean'),
    Physics_Max=('Physics', 'max'),
    Attendance_Mean=('Attendance', 'mean')
)

            Math_Mean  Math_Max  Physics_Mean  Physics_Max  Attendance_Mean
Department
AI & ML     72.653846       100     73.278846          100        82.365385
CSE         71.230000       100     73.820000          100        82.210000
ECE         72.845361       100     73.659794          100        83.164948
EEE         73.052632       100     74.852632          100        82.989474
Mechanical  76.067308       100     76.471154          100        83.923077

Finding and Replacing null's

In [76]:
#there was no nulls in our dataset we are creating the null values to sovle the and explore the null functions
std_original = std.copy()

In [77]:
std_original

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
0,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39,38,40,44,45,75,2
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93,97,87,100,100,94,7
2,ST003,Rahul Patel,Female,ECE,3,A,19,71,81,72,80,96,85,6
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94,86,100,97,96,89,7
4,ST005,Harsha Iyer,Male,CSE,1,C,19,87,67,87,63,72,79,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ST496,Kiran Rao,Male,AI & ML,1,B,22,73,76,72,87,100,96,6
496,ST497,Priya Reddy,Female,CSE,1,B,21,66,58,56,57,73,81,3
497,ST498,Rohit Gupta,Male,EEE,2,A,21,47,59,58,60,62,76,2
498,ST499,Akhil Naidu,Male,AI & ML,2,C,20,77,94,100,93,82,94,6
499,ST500,Sai Naidu,Female,CSE,1,B,18,87,100,78,82,97,97,6

In [78]:
std.loc[5, 'Math'] = None

std.loc[18, 'Attendance'] = None

std.loc[40, 'Department'] = None

std.loc[75, 'Study_Hours'] = None

std.loc[120, 'English'] = None

In [79]:
std

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
0,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39.0,38,40,44.0,45,75.0,2.0
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93.0,97,87,100.0,100,94.0,7.0
2,ST003,Rahul Patel,Female,ECE,3,A,19,71.0,81,72,80.0,96,85.0,6.0
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94.0,86,100,97.0,96,89.0,7.0
4,ST005,Harsha Iyer,Male,CSE,1,C,19,87.0,67,87,63.0,72,79.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ST496,Kiran Rao,Male,AI & ML,1,B,22,73.0,76,72,87.0,100,96.0,6.0
496,ST497,Priya Reddy,Female,CSE,1,B,21,66.0,58,56,57.0,73,81.0,3.0
497,ST498,Rohit Gupta,Male,EEE,2,A,21,47.0,59,58,60.0,62,76.0,2.0
498,ST499,Akhil Naidu,Male,AI & ML,2,C,20,77.0,94,100,93.0,82,94.0,6.0
499,ST500,Sai Naidu,Female,CSE,1,B,18,87.0,100,78,82.0,97,97.0,6.0

In [80]:
#isnull
std.isnull()

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [81]:
std.isnull().sum()

Student_ID      0
Student_Name    0
Gender          0
Department      1
Year            0
Section         0
Age             0
Math            1
Physics         0
Chemistry       0
English         1
Biology         0
Attendance      1
Study_Hours     1
dtype: int64

In [82]:
std['Study_Hours'].isnull().sum()

np.int64(1)

In [83]:
#Display only the rows where Math is missing.
std[std['Math'].isnull()]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
5,ST006,Vikram Naidu,Female,AI & ML,3,B,19,NaN,80,65,77.0,83,79.0,5.0

In [84]:
#Display only the rows where Attendance is missing.
std[std['Attendance'].isnull()]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
18,ST019,Nikhil Singh,Male,AI & ML,2,A,22,99.0,91,94,100.0,93,NaN,8.0

In [85]:
#How many missing values are in each column?
std.isnull().sum()

Student_ID      0
Student_Name    0
Gender          0
Department      1
Year            0
Section         0
Age             0
Math            1
Physics         0
Chemistry       0
English         1
Biology         0
Attendance      1
Study_Hours     1
dtype: int64

In [86]:
#How many total missing values are in the entire dataset?
std.isnull().sum().sum()

np.int64(5)

In [87]:
#Which columns contain at least one missing value?
std.columns[std.isnull().sum() >= 1]

Index(['Department', 'Math', 'English', 'Attendance', 'Study_Hours'], dtype='object')

dropping null values

In [88]:
#Store the cleaned dataset
clean_data = std.dropna()

In [89]:
#Comparing before and after
std.shape

(500, 14)

In [90]:
clean_data.shape

(495, 14)

Filling the null values

In [91]:
std.isnull().sum()

Student_ID      0
Student_Name    0
Gender          0
Department      1
Year            0
Section         0
Age             0
Math            1
Physics         0
Chemistry       0
English         1
Biology         0
Attendance      1
Study_Hours     1
dtype: int64

In [92]:
#filling the avg values for the null values of Math column
std['Math'].fillna(std['Math'].mean())
std['Math'] = std['Math'].fillna(0)

In [93]:
#Replace missing Math marks with the average Math mark.
std['Math'] = std['Math'].fillna(std['Math'].mean())

In [94]:
std['Math'].isnull().sum() #checking the null values after filling them with avg values

np.int64(0)

In [95]:
#Replace missing Attendance with the average Attendance.
std['Attendance'] = std['Attendance'].fillna(std['Attendance'].mean())

In [96]:
#Replace missing Department with "Unknown".
std['Department'] = std['Department'].fillna('Unknown')

In [97]:
#Replace missing Study_Hours with the median Study_Hours.
std['Study_Hours'] = std['Study_Hours'].fillna(std['Study_Hours'].median())

In [98]:
#Replace missing English marks with the average English mark.
std['English'] = std['English'].fillna(std['English'].mean())

Duplicates

In [99]:
#first let's creates the duplicates because there was no duplicatesin our current dataset
duplicates_data = std.iloc[:5]
duplicates_data

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
0,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39.0,38,40,44.0,45,75.0,2.0
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93.0,97,87,100.0,100,94.0,7.0
2,ST003,Rahul Patel,Female,ECE,3,A,19,71.0,81,72,80.0,96,85.0,6.0
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94.0,86,100,97.0,96,89.0,7.0
4,ST005,Harsha Iyer,Male,CSE,1,C,19,87.0,67,87,63.0,72,79.0,5.0

In [100]:
std = pd.concat([std, duplicates_data], ignore_index=True)

In [101]:
std

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
0,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39.0,38,40,44.0,45,75.0,2.0
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93.0,97,87,100.0,100,94.0,7.0
2,ST003,Rahul Patel,Female,ECE,3,A,19,71.0,81,72,80.0,96,85.0,6.0
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94.0,86,100,97.0,96,89.0,7.0
4,ST005,Harsha Iyer,Male,CSE,1,C,19,87.0,67,87,63.0,72,79.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39.0,38,40,44.0,45,75.0,2.0
501,ST002,Varun Iyer,Male,Mechanical,2,C,22,93.0,97,87,100.0,100,94.0,7.0
502,ST003,Rahul Patel,Female,ECE,3,A,19,71.0,81,72,80.0,96,85.0,6.0
503,ST004,Harsha Iyer,Female,CSE,4,C,18,94.0,86,100,97.0,96,89.0,7.0
504,ST005,Harsha Iyer,Male,CSE,1,C,19,87.0,67,87,63.0,72,79.0,5.0

In [102]:
#checking the duplicates
std.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
500     True
501     True
502     True
503     True
504     True
Length: 505, dtype: bool

In [103]:
std.duplicated().sum()

np.int64(5)

In [104]:
std[std.duplicated()]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
500,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39.0,38,40,44.0,45,75.0,2.0
501,ST002,Varun Iyer,Male,Mechanical,2,C,22,93.0,97,87,100.0,100,94.0,7.0
502,ST003,Rahul Patel,Female,ECE,3,A,19,71.0,81,72,80.0,96,85.0,6.0
503,ST004,Harsha Iyer,Female,CSE,4,C,18,94.0,86,100,97.0,96,89.0,7.0
504,ST005,Harsha Iyer,Male,CSE,1,C,19,87.0,67,87,63.0,72,79.0,5.0

In [105]:
remove_duplicates = std.drop_duplicates()

In [106]:
remove_duplicates.shape

(500, 14)

In [107]:
#How many duplicate rows are present?
std.duplicated().sum()

np.int64(5)

In [108]:
#Display only duplicate rows.
std[std.duplicated()]

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours
500,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39.0,38,40,44.0,45,75.0,2.0
501,ST002,Varun Iyer,Male,Mechanical,2,C,22,93.0,97,87,100.0,100,94.0,7.0
502,ST003,Rahul Patel,Female,ECE,3,A,19,71.0,81,72,80.0,96,85.0,6.0
503,ST004,Harsha Iyer,Female,CSE,4,C,18,94.0,86,100,97.0,96,89.0,7.0
504,ST005,Harsha Iyer,Male,CSE,1,C,19,87.0,67,87,63.0,72,79.0,5.0

In [109]:
clean_std = std.drop_duplicates().copy()

In [110]:
#before
std.shape

(505, 14)

In [111]:
#after
clean_std.shape

(500, 14)

Feature Engineering

In [112]:
#Create a new column:Total_Marks
clean_std['Total_Marks'] = clean_std['Math'] + clean_std['Physics'] + clean_std['Chemistry'] + clean_std['English'] + clean_std['Biology']

In [113]:
clean_std['Total_Marks']

0      206.0
1      477.0
2      400.0
3      473.0
4      376.0
       ...
495    408.0
496    310.0
497    286.0
498    446.0
499    444.0
Name: Total_Marks, Length: 500, dtype: float64

In [114]:
#Average Marks
clean_std['Average_Marks'] = clean_std['Total_Marks'] / 5

In [115]:
#percentage
clean_std['Percentage'] = (clean_std['Total_Marks'] / 500) * 100

In [116]:
#Result

In [117]:
#Display only:

#Student_Name
#Total_Marks
#Average_Marks
clean_std[['Student_Name','Total_Marks','Average_Marks']]

     Student_Name  Total_Marks  Average_Marks
0    Sneha Sharma        206.0           41.2
1      Varun Iyer        477.0           95.4
2     Rahul Patel        400.0           80.0
3     Harsha Iyer        473.0           94.6
4     Harsha Iyer        376.0           75.2
..            ...          ...            ...
495     Kiran Rao        408.0           81.6
496   Priya Reddy        310.0           62.0
497   Rohit Gupta        286.0           57.2
498   Akhil Naidu        446.0           89.2
499     Sai Naidu        444.0           88.8

[500 rows x 3 columns]

In [118]:
clean_std.sort_values('Average_Marks', ascending=False)[['Student_Name','Average_Marks']]

      Student_Name  Average_Marks
79      Divya Iyer          100.0
38      Neha Kumar          100.0
134      Sai Reddy          100.0
382   Aditya Patel           99.6
130    Aisha Kumar           99.4
..             ...            ...
478  Harsha Sharma           38.8
361    Pooja Reddy           38.4
83     Sneha Naidu           37.8
190      Kiran Rao           37.4
153    Akhil Gupta           36.8

[500 rows x 2 columns]

apply function

In [119]:
#Create the Result column.
clean_std.columns

Index(['Student_ID', 'Student_Name', 'Gender', 'Department', 'Year', 'Section',
       'Age', 'Math', 'Physics', 'Chemistry', 'English', 'Biology',
       'Attendance', 'Study_Hours', 'Total_Marks', 'Average_Marks',
       'Percentage'],
      dtype='object')

In [120]:
def result(marks):
  if marks >= 250:
    return 'Pass'
  else:
    return 'Fail'

In [121]:
clean_std['Result'] = clean_std['Total_Marks'].apply(result)

In [122]:
clean_std

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,English,Biology,Attendance,Study_Hours,Total_Marks,Average_Marks,Percentage,Result
0,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39.0,38,40,44.0,45,75.0,2.0,206.0,41.2,41.2,Fail
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93.0,97,87,100.0,100,94.0,7.0,477.0,95.4,95.4,Pass
2,ST003,Rahul Patel,Female,ECE,3,A,19,71.0,81,72,80.0,96,85.0,6.0,400.0,80.0,80.0,Pass
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94.0,86,100,97.0,96,89.0,7.0,473.0,94.6,94.6,Pass
4,ST005,Harsha Iyer,Male,CSE,1,C,19,87.0,67,87,63.0,72,79.0,5.0,376.0,75.2,75.2,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ST496,Kiran Rao,Male,AI & ML,1,B,22,73.0,76,72,87.0,100,96.0,6.0,408.0,81.6,81.6,Pass
496,ST497,Priya Reddy,Female,CSE,1,B,21,66.0,58,56,57.0,73,81.0,3.0,310.0,62.0,62.0,Pass
497,ST498,Rohit Gupta,Male,EEE,2,A,21,47.0,59,58,60.0,62,76.0,2.0,286.0,57.2,57.2,Pass
498,ST499,Akhil Naidu,Male,AI & ML,2,C,20,77.0,94,100,93.0,82,94.0,6.0,446.0,89.2,89.2,Pass
499,ST500,Sai Naidu,Female,CSE,1,B,18,87.0,100,78,82.0,97,97.0,6.0,444.0,88.8,88.8,Pass

In [123]:
#Create the Grade column.
def grade(marks):

    if marks >= 450:
        return 'A'

    elif marks >= 400:
        return 'B'

    elif marks >= 350:
        return 'C'

    elif marks >= 300:
        return 'D'

    elif marks >= 250:
        return 'E'

    else:
        return 'F'

In [124]:
clean_std['Grade'] = clean_std['Total_Marks'].apply(grade)

In [125]:
clean_std['Grade']

0      F
1      A
2      B
3      A
4      C
      ..
495    B
496    D
497    E
498    B
499    B
Name: Grade, Length: 500, dtype: object

In [126]:
clean_std.columns

Index(['Student_ID', 'Student_Name', 'Gender', 'Department', 'Year', 'Section',
       'Age', 'Math', 'Physics', 'Chemistry', 'English', 'Biology',
       'Attendance', 'Study_Hours', 'Total_Marks', 'Average_Marks',
       'Percentage', 'Result', 'Grade'],
      dtype='object')

In [127]:
def Performance(percentange):
  if percentange >= 90:
    return 'Excellent'
  elif percentange >= 75 and percentange < 90:
    return 'Good'
  elif percentange >= 60 and percentange < 75:
    return 'Average'
  else:
    return 'Poor'

In [128]:
clean_std['Performance'] = clean_std['Percentage'].apply(Performance)

In [129]:
clean_std[['Student_Name','Average_Marks','Grade','Performance']]

     Student_Name  Average_Marks Grade Performance
0    Sneha Sharma           41.2     F        Poor
1      Varun Iyer           95.4     A   Excellent
2     Rahul Patel           80.0     B        Good
3     Harsha Iyer           94.6     A   Excellent
4     Harsha Iyer           75.2     C        Good
..            ...            ...   ...         ...
495     Kiran Rao           81.6     B        Good
496   Priya Reddy           62.0     D     Average
497   Rohit Gupta           57.2     E        Poor
498   Akhil Naidu           89.2     B        Good
499     Sai Naidu           88.8     B        Good

[500 rows x 4 columns]

In [130]:
#How many students got
#A
#B
#C
#D
#F
clean_std['Grade'].value_counts()

Grade
A    137
C     78
E     74
D     73
B     70
F     68
Name: count, dtype: int64

lamda function

In [131]:
#scholarship
clean_std['Scholarship'] = clean_std['Percentage'].apply( lambda x: 'Eligible' if x > 85 else 'Not Eligible')

In [132]:
#Attendance_Status
clean_std['Attendance_Status'] = clean_std['Attendance'].apply(lambda x: 'Good' if x > 75 else 'Low')

In [133]:
#Study_Level
clean_std['Study_Level'] = clean_std['Study_Hours'].apply(lambda x : 'High' if x >= 6 else 'Low')

In [134]:
#Performance_Level
#≥90 → Excellent
#≥75 → Good
#≥60 → Average
#Otherwise → Poor
clean_std['Performance_Level'] = clean_std['Percentage'].apply(lambda x : 'Excellent' if x >= 90 else 'Good' if x >=75 else 'Average' if x >= 60 else 'Poor')

merge() --- > so we have to create the another dataset sample to merge

In [135]:
placements = pd.DataFrame()

In [136]:
placements['Student_ID'] = clean_data['Student_ID']

In [137]:
placements

    Student_ID
0        ST001
1        ST002
2        ST003
3        ST004
4        ST005
..         ...
495      ST496
496      ST497
497      ST498
498      ST499
499      ST500

[495 rows x 1 columns]

In [138]:
companies = [
    "TCS",
    "Infosys",
    "Wipro",
    "Accenture",
    "Cognizant",
    "Capgemini",
    "Microsoft",
    "Google",
    "Amazon",
    "Deloitte"
]

In [139]:
import numpy as np

In [140]:
std.shape

(505, 14)

In [141]:
clean_data.shape

(495, 14)

In [142]:
clean_std.shape

(500, 24)

In [143]:
placements['Company'] = np.random.choice(companies, size=len(placements))

In [144]:
placements["Placement_Status"] = np.random.choice(
    ["Placed", "Not Placed"],
    size=len(placements),
    p=[0.7, 0.3]
)

In [145]:
placements["Package_LPA"] = np.random.randint(3, 25, size=len(placements))

In [146]:
placements["Interview_Rounds"] = np.random.randint(1, 6, size=len(placements))

In [147]:
placements.loc[
    placements["Placement_Status"] == "Not Placed",
    "Company"
] = "Not Placed"

placements.loc[
    placements["Placement_Status"] == "Not Placed",
    "Package_LPA"
] = 0

placements.loc[
    placements["Placement_Status"] == "Not Placed",
    "Interview_Rounds"
] = 0

In [148]:
placements.to_csv("placements.csv", index=False)

In [150]:
#creating the merging
merged_df = pd.merge(
    clean_std,
    placements,
    on='Student_ID'
)

In [151]:
merged_df

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,...,Grade,Performance,Scholarship,Attendance_Status,Study_Level,Performance_Level,Company,Placement_Status,Package_LPA,Interview_Rounds
0,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39.0,38,40,...,F,Poor,Not Eligible,Low,Low,Poor,Not Placed,Not Placed,0,0
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93.0,97,87,...,A,Excellent,Eligible,Good,High,Excellent,Infosys,Placed,7,4
2,ST003,Rahul Patel,Female,ECE,3,A,19,71.0,81,72,...,B,Good,Not Eligible,Good,High,Good,TCS,Placed,14,4
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94.0,86,100,...,A,Excellent,Eligible,Good,High,Excellent,Not Placed,Not Placed,0,0
4,ST005,Harsha Iyer,Male,CSE,1,C,19,87.0,67,87,...,C,Good,Not Eligible,Good,Low,Good,Not Placed,Not Placed,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,ST496,Kiran Rao,Male,AI & ML,1,B,22,73.0,76,72,...,B,Good,Not Eligible,Good,High,Good,Infosys,Placed,9,5
491,ST497,Priya Reddy,Female,CSE,1,B,21,66.0,58,56,...,D,Average,Not Eligible,Good,Low,Average,TCS,Placed,18,1
492,ST498,Rohit Gupta,Male,EEE,2,A,21,47.0,59,58,...,E,Poor,Not Eligible,Good,Low,Poor,Not Placed,Not Placed,0,0
493,ST499,Akhil Naidu,Male,AI & ML,2,C,20,77.0,94,100,...,B,Good,Eligible,Good,High,Good,Wipro,Placed,21,3
494,ST500,Sai Naidu,Female,CSE,1,B,18,87.0,100,78,...,B,Good,Eligible,Good,High,Good,Microsoft,Placed,5,2

In [152]:
merged_df.shape

(495, 28)

In [153]:
#Display the first five rows of merged_df
merged_df.head(5)

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,...,Grade,Performance,Scholarship,Attendance_Status,Study_Level,Performance_Level,Company,Placement_Status,Package_LPA,Interview_Rounds
0,ST001,Sneha Sharma,Female,AI & ML,2,A,18,39.0,38,40,...,F,Poor,Not Eligible,Low,Low,Poor,Not Placed,Not Placed,0,0
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93.0,97,87,...,A,Excellent,Eligible,Good,High,Excellent,Infosys,Placed,7,4
2,ST003,Rahul Patel,Female,ECE,3,A,19,71.0,81,72,...,B,Good,Not Eligible,Good,High,Good,TCS,Placed,14,4
3,ST004,Harsha Iyer,Female,CSE,4,C,18,94.0,86,100,...,A,Excellent,Eligible,Good,High,Excellent,Not Placed,Not Placed,0,0
4,ST005,Harsha Iyer,Male,CSE,1,C,19,87.0,67,87,...,C,Good,Not Eligible,Good,Low,Good,Not Placed,Not Placed,0,0

In [154]:
#How many columns and rows ?
clean_std.shape

(500, 24)

In [155]:
placements.shape

(495, 5)

In [156]:
merged_df.shape

(495, 28)

In [157]:
#Display only
#Student_Name
#Department
#Company
#Package_LPA
merged_df[['Student_Name','Department','Company','Package_LPA']]

     Student_Name  Department     Company  Package_LPA
0    Sneha Sharma     AI & ML  Not Placed            0
1      Varun Iyer  Mechanical     Infosys            7
2     Rahul Patel         ECE         TCS           14
3     Harsha Iyer         CSE  Not Placed            0
4     Harsha Iyer         CSE  Not Placed            0
..            ...         ...         ...          ...
490     Kiran Rao     AI & ML     Infosys            9
491   Priya Reddy         CSE         TCS           18
492   Rohit Gupta         EEE  Not Placed            0
493   Akhil Naidu     AI & ML       Wipro           21
494     Sai Naidu         CSE   Microsoft            5

[495 rows x 4 columns]

In [158]:
#How many students are placed?
merged_df.columns

Index(['Student_ID', 'Student_Name', 'Gender', 'Department', 'Year', 'Section',
       'Age', 'Math', 'Physics', 'Chemistry', 'English', 'Biology',
       'Attendance', 'Study_Hours', 'Total_Marks', 'Average_Marks',
       'Percentage', 'Result', 'Grade', 'Performance', 'Scholarship',
       'Attendance_Status', 'Study_Level', 'Performance_Level', 'Company',
       'Placement_Status', 'Package_LPA', 'Interview_Rounds'],
      dtype='object')

In [164]:
merged_df[merged_df['Placement_Status'] == 'Placed'].count()

Student_ID           336
Student_Name         336
Gender               336
Department           336
Year                 336
Section              336
Age                  336
Math                 336
Physics              336
Chemistry            336
English              336
Biology              336
Attendance           336
Study_Hours          336
Total_Marks          336
Average_Marks        336
Percentage           336
Result               336
Grade                336
Performance          336
Scholarship          336
Attendance_Status    336
Study_Level          336
Performance_Level    336
Company              336
Placement_Status     336
Package_LPA          336
Interview_Rounds     336
dtype: int64

In [165]:
#Find the average package offered by each company.
merged_df.groupby('Company')['Package_LPA'].mean()

Company
Accenture     12.323529
Amazon        13.645161
Capgemini     13.450000
Cognizant     13.741935
Deloitte      12.424242
Google        14.885714
Infosys       12.354839
Microsoft     13.941176
Not Placed     0.000000
TCS           14.100000
Wipro         14.925926
Name: Package_LPA, dtype: float64

In [173]:
#Which company hired the most students?
merged_df[merged_df['Placement_Status'] == 'Placed'].groupby('Company')['Student_ID'].count().sort_values(ascending=False).head(1)
#better solution
merged_df[
    merged_df['Placement_Status']=='Placed'
]['Company'].value_counts().head(1)

Company
TCS    40
Name: count, dtype: int64

In [170]:
#Find the average package department-wise.
merged_df.groupby('Department')['Package_LPA'].mean()

Department
AI & ML       9.392157
CSE           9.530000
ECE           8.625000
EEE           9.265957
Mechanical    9.233010
Name: Package_LPA, dtype: float64

In [171]:
#Display only placed students.
merged_df[merged_df['Placement_Status'] == 'Placed']

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,...,Grade,Performance,Scholarship,Attendance_Status,Study_Level,Performance_Level,Company,Placement_Status,Package_LPA,Interview_Rounds
1,ST002,Varun Iyer,Male,Mechanical,2,C,22,93.0,97,87,...,A,Excellent,Eligible,Good,High,Excellent,Infosys,Placed,7,4
2,ST003,Rahul Patel,Female,ECE,3,A,19,71.0,81,72,...,B,Good,Not Eligible,Good,High,Good,TCS,Placed,14,4
5,ST007,Divya Patel,Female,EEE,3,C,22,80.0,78,78,...,C,Average,Not Eligible,Good,Low,Average,Accenture,Placed,22,5
6,ST008,Priya Singh,Female,ECE,1,A,22,90.0,85,82,...,A,Excellent,Eligible,Good,High,Excellent,Amazon,Placed,20,2
7,ST009,Akhil Patel,Female,AI & ML,2,C,22,92.0,82,76,...,C,Good,Not Eligible,Good,Low,Good,Infosys,Placed,22,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,ST494,Rahul Iyer,Female,AI & ML,3,A,19,79.0,72,86,...,C,Good,Not Eligible,Good,Low,Good,TCS,Placed,19,4
490,ST496,Kiran Rao,Male,AI & ML,1,B,22,73.0,76,72,...,B,Good,Not Eligible,Good,High,Good,Infosys,Placed,9,5
491,ST497,Priya Reddy,Female,CSE,1,B,21,66.0,58,56,...,D,Average,Not Eligible,Good,Low,Average,TCS,Placed,18,1
493,ST499,Akhil Naidu,Male,AI & ML,2,C,20,77.0,94,100,...,B,Good,Eligible,Good,High,Good,Wipro,Placed,21,3
494,ST500,Sai Naidu,Female,CSE,1,B,18,87.0,100,78,...,B,Good,Eligible,Good,High,Good,Microsoft,Placed,5,2

In [172]:
#Find the Top 10 highest package students.
merged_df.sort_values('Package_LPA',ascending=False).head(10)

,Student_ID,Student_Name,Gender,Department,Year,Section,Age,Math,Physics,Chemistry,...,Grade,Performance,Scholarship,Attendance_Status,Study_Level,Performance_Level,Company,Placement_Status,Package_LPA,Interview_Rounds
374,ST380,Keerthi Iyer,Male,Mechanical,2,B,19,68.0,72,60,...,D,Average,Not Eligible,Low,Low,Average,TCS,Placed,24,1
76,ST081,Kiran Naidu,Male,AI & ML,3,A,21,68.0,53,39,...,E,Poor,Not Eligible,Good,Low,Poor,Microsoft,Placed,24,5
413,ST419,Vikram Gupta,Female,AI & ML,2,C,22,100.0,100,100,...,A,Excellent,Eligible,Good,High,Excellent,TCS,Placed,24,2
422,ST428,Nikhil Sharma,Male,AI & ML,4,B,19,41.0,50,51,...,F,Poor,Not Eligible,Low,Low,Poor,Wipro,Placed,24,1
341,ST347,Divya Rao,Female,ECE,3,B,19,66.0,69,75,...,D,Average,Not Eligible,Good,Low,Average,Google,Placed,24,3
267,ST273,Vikram Patel,Male,EEE,4,C,22,66.0,55,77,...,D,Average,Not Eligible,Low,Low,Average,Wipro,Placed,24,4
189,ST195,Nikhil Gupta,Female,EEE,4,A,20,100.0,95,93,...,A,Excellent,Eligible,Good,High,Excellent,Accenture,Placed,24,3
132,ST138,Kiran Rao,Female,CSE,3,A,22,99.0,99,80,...,A,Excellent,Eligible,Good,High,Excellent,Capgemini,Placed,24,1
30,ST033,Divya Rao,Male,CSE,4,A,21,79.0,82,67,...,C,Average,Not Eligible,Good,Low,Average,Amazon,Placed,24,2
231,ST237,Divya Rao,Male,ECE,2,C,20,65.0,70,71,...,D,Average,Not Eligible,Good,Low,Average,Cognizant,Placed,24,2

Pivot Tables

In [174]:
#Create a Pivot Table showing:

#Rows → Department
#Values → Attendance
#Function → Average
pd.pivot_table(
    merged_df,
    index = 'Department',
    values = 'Attendance',
    aggfunc = 'mean'
)

            Attendance
Department
AI & ML      82.264706
CSE          82.210000
ECE          83.062500
EEE          82.978723
Mechanical   84.000000

In [175]:
#Rows → Department
#Values → Average_Marks
#Function → Average
pd.pivot_table(
    merged_df,
    index = 'Department',
    values = 'Average_Marks',
    aggfunc = 'mean'
)

            Average_Marks
Department
AI & ML         72.464706
CSE             72.468000
ECE             72.841667
EEE             73.778723
Mechanical      76.198058

In [176]:
#Rows → Department

#Columns → Placement_Status

#Values → Student_ID

#Function → Count
pd.pivot_table(
    merged_df,
    index = 'Department',
    columns = 'Placement_Status',
    values = 'Student_ID',
    aggfunc = 'count'
)

Placement_Status  Not Placed  Placed
Department
AI & ML                   33      69
CSE                       32      68
ECE                       32      64
EEE                       31      63
Mechanical                31      72